version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./env
    ports:
      - 5432:5432
    volumes:
      - ./data/db_vol:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-network

  api_server:
    image: server_image
    restart: always
    build:
      context: ./api_server
    env_file:
      - ./env
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  client:
    ports:
      - 9000:9000
    build:
      context: ./client/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
